Restaurant.new(name: "McDonalds", category: "american", address: "75001 Paris")
Restaurant.new(name: "pasta milano", category: "italian", address: "London")
Restaurant.new(name: "sukiyaki", category: "japanese", address: "Tokyo")
Restaurant.new(name: "robi", category: "italian", address: "New York")
Restaurant.new(name: "thairesto", category: "thai", address: "75018 Paris")
